name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "spring.datasource.url=jdbc:mysql://${{ secrets.DB_HOST }}:3306/${{ secrets.DB_NAME }}" > ~/app/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> ~/app/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> ~/app/application.properties
          echo "spring.profiles.active=prod" >> ~/app/application.properties
          # 나머지 properties 설정들 추가
          cd ~/app
          ./deploy.sh
