name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 히스토리 가져오기
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Debug project structure
        run: |
          echo "===== Looking for Controller files ====="
          find src -name "*.java" | grep -i controller
          echo "===== Looking for Store related files ====="
          find src -name "*.java" | grep -i store
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew clean build -x test
      
      - name: Verify JAR contents
        run: |
          echo "===== Checking JAR contents ====="
          jar tf build/libs/SOMA-0.0.1-SNAPSHOT.jar | grep -i controller
          jar tf build/libs/SOMA-0.0.1-SNAPSHOT.jar | grep -i store
          jar tf build/libs/SOMA-0.0.1-SNAPSHOT.jar | grep -i dto
      
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/SOMA-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app"
      
      - name: Create application.properties on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > /home/ubuntu/app/application.properties << 'EOL'
            spring.datasource.url=jdbc:mysql://${{ secrets.DB_HOST }}:3306/${{ secrets.DB_NAME }}
            spring.datasource.username=${{ secrets.DB_USERNAME }}
            spring.datasource.password=${{ secrets.DB_PASSWORD }}
            spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
            spring.jpa.hibernate.ddl-auto=update
            spring.jpa.show-sql=true
            spring.jpa.properties.hibernate.format_sql=true
            spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
            server.port=8080
            app.cors.allowed-origins=https://kuad-archive.com
            app.cors.allowed-methods=GET,POST,PUT,DELETE
            app.cors.allowed-headers=*
            app.cors.max-age=3600
            EOL
      
      - name: Update deploy.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cat > /home/ubuntu/app/deploy.sh << 'EOF'
            #!/bin/bash
            # deploy.sh - always exit 0
            set +e
            cd /home/ubuntu/app || exit 0
            echo "Current working directory: $(pwd)"
            echo "Listing files in /home/ubuntu/app:"
            ls -l
            if pgrep -f "java -jar" > /dev/null; then
              echo "Found running java process(es), killing them..."
              kill -15 $(pgrep -f "java -jar") >/dev/null 2>&1
              sleep 5
            fi
            echo "Running: java -jar /home/ubuntu/app/SOMA-0.0.1-SNAPSHOT.jar --spring.config.location=file:/home/ubuntu/app/application.properties"
            nohup java -jar /home/ubuntu/app/SOMA-0.0.1-SNAPSHOT.jar --spring.config.location=file:/home/ubuntu/app/application.properties > nohup.out 2>&1 &
            sleep 2
            echo "Application started"
            exit 0
            EOF
      
      - name: Set execute permission on deploy.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: chmod +x /home/ubuntu/app/deploy.sh
      
      - name: Run deploy.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: bash /home/ubuntu/app/deploy.sh || true
      
      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "===== Checking running Java process ====="
            ps aux | grep java
            echo "===== Checking application logs ====="
            tail -n 50 /home/ubuntu/app/nohup.out
            echo "===== Testing API endpoints ====="
            curl -v http://localhost:8080/api/members/search?keyword=
            curl -v http://localhost:8080/api/store/teams
