name: Deploy to EC2

on:
 push:
   branches:
     - main

jobs:
 deploy:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2

   - name: Set up JDK 17
     uses: actions/setup-java@v2
     with:
       java-version: '17'
       distribution: 'adopt'

   - name: Grant execute permission for gradlew
     run: chmod +x gradlew

   - name: Build with Gradle
     run: ./gradlew clean build -x test

   - name: Copy files to EC2
     uses: appleboy/scp-action@master
     with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USERNAME }}
       key: ${{ secrets.EC2_SSH_KEY }}
       source: "build/libs/*.jar"
       target: "/home/ubuntu/app"
       strip_components: 2

   - name: Execute deploy script
     uses: appleboy/ssh-action@master
     with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USERNAME }}
       key: ${{ secrets.EC2_SSH_KEY }}
       script: |
         echo "spring.datasource.url=jdbc:mysql://${{ secrets.DB_HOST }}:3306/${{ secrets.DB_NAME }}" > ~/app/application.properties
         echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> ~/app/application.properties
         echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> ~/app/application.properties
         echo "spring.profiles.active=prod" >> ~/app/application.properties
         echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> ~/app/application.properties
         echo "spring.jpa.hibernate.ddl-auto=update" >> ~/app/application.properties
         echo "spring.jpa.show-sql=true" >> ~/app/application.properties
         echo "spring.jpa.properties.hibernate.format_sql=true" >> ~/app/application.properties
         echo "spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect" >> ~/app/application.properties
         echo "server.port=8080" >> ~/app/application.properties
         echo "app.cors.allowed-origins=https://kuad-archive.com" >> ~/app/application.properties
         echo "app.cors.allowed-methods=GET,POST,PUT,DELETE" >> ~/app/application.properties
         echo "app.cors.allowed-headers=*" >> ~/app/application.properties
         echo "app.cors.max-age=3600" >> ~/app/application.properties
         cd ~/app
         chmod +x deploy.sh
         ./deploy.sh
